[package]
name = "encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { path = "D:\\Probleme RUST\\Rust Laboratories\\lab09\\base64" }
clap = "4.4.10"